name: build and deploy

on:
  push:
    branches:
      - master

jobs:
  build_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_B64 }}'

      - name: Setup gcloud cli
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure docker and install gcloud components
        run: |
          gcloud auth configure-docker --quiet
          gcloud components install beta --quiet

      - name: Build and Push
        run: |
          docker build -t gcr.io/tendermint/ignite-installer:${GITHUB_SHA::8} .
          docker tag gcr.io/tendermint/ignite-installer:${GITHUB_SHA::8} gcr.io/tendermint/ignite-installer:latest
          docker push gcr.io/tendermint/ignite-installer:${GITHUB_SHA::8}
          docker push gcr.io/tendermint/ignite-installer:latest

      - name: Deploy to cloud run
        run: gcloud beta run deploy ignite-installer --quiet
          --region us-east1
          --platform managed
          --allow-unauthenticated
          --image gcr.io/tendermint/ignite-installer:latest
          --concurrency 80
          --memory 128Mi
          --cpu 1000m
          --max-instances 3
          --port 8080
          --timeout 300s
          --update-env-vars USER=ignite-hq
